/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test_gradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        final String specificationVersion = App.class.getPackage().getSpecificationVersion();
        final String implementationVersion = App.class.getPackage().getImplementationVersion();
        System.out.println("SpecificationVersion =[" + specificationVersion + "]");
        System.out.println("ImplementationVersion=[" + implementationVersion + "]");
    }
}
